name: Deploy to FTP Server

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy Action
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Step 2: FTP Deploy Action
      - name: FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }} 
